### ISSUE TITLE
Doesn't support multiple cursors

### ISSUE THREAD

**Issue by ghost** [wangchunsen/vscode-bracket-select#1] opened 2019-05-22 14:28 UTC
When trying to select between brackets when multiple cursors are present it only selects at the original cursor location.

**Comment by wangchunsen** [comment] 2019-05-23 01:17
Duplicate of # Yes, It does not support multiple cursors for now. But this should be a good point to make an enhancement.

**Comment by kanlukasz** [comment] 2020-03-31 11:25
I also miss this functionality very much.
Is there any chance to add this?

_Sorry for no PR. I'm just a php dev_

**Closed** 2020-05-18 04:22 UTC
Labels: enhancement

**Comment by kanlukasz** [comment] 2020-05-20 06:54
Was it pushed to the marketplace?
I don't see updates in VSCode
